### ISSUE TITLE
Use case: Present Data

### ISSUE THREAD

**Issue by ahoffer** [alacer/renaissance#13]
This use case describes one part of the end-to-end story.

<hr>

_I could use some help with this one_

<hr>

**Actors** User, Renaissance Trelliscope, Renaissance Web App, Local App
**Preconditions** The appropriate key file(s) are accessible from the user's file system.
1. User navigates to Renaissance Trelliscope. via Browser
2. Renaissance Trelliscope presents Users with a list of result sets to choose from.
3. User chooses desired result set.
4. Renaissance Trelliscopeasks User if the results should be decloaked.
5. User confirms that data should be decloaked.
6. Renaissance re-directs browser to Renaissance Web App and passes it URL to selected result set.
7. Browser downloads Local App and beings running it.
8. Local App prompts user for key file(s).
9. User selects local key file(s).
10. Local App loads key file data into memory.
11. Local App requests HTML stream from Renaissance Trelliscope.
12. Renaissance Trelliscope begins sending HTML stream to Local App
13. Local App reads Renaissance Trelliscope data and substitutes real data values in place of cloaked data values.
14. Local App adds/re-writes <div> node in Browser's DOM with de-cloaked HTML stream from Renaissance.
15. Browser renders Renaissance results to User.

**Comment by edsarausad** [comment]
Thanks for framing this up!  Questions:

1)  (Getting into design) does the use case start from a "Decloak" button in the left nav bar (current button should be renamed to "Cloak")?
2)  Is a "result set" simply a set of data stored on our back-end?  Or can it further filtered in the UI (table/univariate/multi-variate)?
3)  How would multiple key files be handled?  (Would one key file not suffice?)
4)  Is the rendered result the same Renaissance analysis plots or a downloadable file (PDF)?
