### ISSUE TITLE
Console error messages

### ISSUE THREAD

**Issue by ahoffer** [alacer/renaissance#14]
Copy of the error messages Chrome's console log.
<hr>

![image](https://cloud.githubusercontent.com/assets/133284/5636451/148e8172-95a7-11e4-9e24-db029690b0a5.png)

**Comment by krseibel** [comment]
Errors fixed.  Please note--the highcharts error is due to an error in the config.yml file from the RCharts library (find it via 3.1\rCharts\libraries\highcharts).  I'll submit a pull request to RCharts to have the error fixed, but until then, the highcharts code will remain.
